import { checkoutPageLister } from "../../Modules/CheckoutPageLister/CheckoutPageLister.js";
import { addNewAddress } from "../../Modules/addNewAddress/addNewAddress.js";
import { addNewAddressToDB } from "../../Modules/addNewAddressToDB/addNewAddressToDB.js";
import { addressLister } from "../../Modules/addressLister/addressLister.js";
import { addressShowAndHide } from "../../Modules/addressShowAndHide/addressShowAndHide.js";
import { shippingShowAndHide } from "../../Modules/shippingShowAndHide/shippingShowAndHide.js";
import { dateMaker } from "../../Modules/dateMaker/dateMaker.js";
import { shippingPrice } from "../../Modules/ShippingPrice/ShippingPrice.js";
import { shouldPayShippingAdder } from "../../Modules/shouldPayShippingAdder/shouldPayShippingAdder.js";
import { promoCodeAdder } from "../../Modules/PromoCodeAdder/PromoCodeAdder.js";
import { removePromo } from "../../Modules/RemovePromo/RemovePromo.js";
import { paymentOpen } from "../../Modules/PaymentOpen/PaymentOpen.js";
import { paymentClose } from "../../Modules/PaymentClose/PaymentClose.js";
import { confirmPayment } from "../../Modules/ConfirmPayment/ConfirmPayment.js";

checkoutPageLister();
addNewAddress();
addNewAddressToDB();
addressLister();
addressShowAndHide();
shippingShowAndHide();
dateMaker();
shippingPrice();
shouldPayShippingAdder();
promoCodeAdder();
removePromo();
paymentOpen();
paymentClose();
confirmPayment();